
# Logic operations and ternary logic experiments

SELECT TRUE AS `OPERANDS`
    UNION
SELECT FALSE
    UNION
SELECT NULL;

SELECT 'AND' AS `OPERATIONS`
    UNION
SELECT 'OR'
    UNION
SELECT 'NOT'
    UNION
SELECT 'XOR';

SELECT # Ternary logic - AND OPERATOR
    'NULL' AS `AND`,
    NULL AND NULL AS `NULL`,
    NULL AND TRUE AS `TRUE`,
    NULL AND FALSE AS `FALSE`
UNION
SELECT
    'TRUE',
    TRUE AND NULL,
    TRUE AND TRUE,
    TRUE AND FALSE
UNION
SELECT
    'FALSE',
    FALSE AND NULL,
    FALSE AND TRUE,
    FALSE AND FALSE;
    
SELECT # OR OPERATOR
    'NULL' AS `OR`,
    NULL OR NULL AS `NULL`,
    NULL OR TRUE AS `TRUE`,
    NULL OR FALSE AS `FALSE`
UNION
SELECT
    'TRUE',
    TRUE OR NULL,
    TRUE OR TRUE,
    TRUE OR FALSE
UNION
SELECT
    'FALSE',
    FALSE OR NULL,
    FALSE OR TRUE,
    FALSE OR FALSE;
    
SELECT # NOT OPERATOR
    'NOT' AS ``,
    NOT TRUE AS `TRUE`,
    NOT FALSE AS `FALSE`,
    NOT NULL AS `NULL`;

SELECT # XOR OPERATOR
    'NULL' AS `XOR`,
    NULL XOR NULL AS `NULL`,
    NULL XOR TRUE AS `TRUE`,
    NULL XOR FALSE AS `FALSE`
UNION
SELECT
    'TRUE',
    TRUE XOR NULL,
    TRUE XOR TRUE,
    TRUE XOR FALSE
UNION
SELECT
    'FALSE',
    FALSE XOR NULL,
    FALSE XOR TRUE,
    FALSE XOR FALSE;
    